import { useState } from 'react';
import { PaintInputs, PaintCalculationResult } from '../types';
import { Check, Copy, AlertTriangle, Package, Printer, Info, Coins } from 'lucide-react';

interface ResultPanelProps {
  inputs: PaintInputs;
  result: PaintCalculationResult;
}

export function ResultPanel({ inputs, result }: ResultPanelProps) {
  const [copied, setCopied] = useState(false);

  const isRoomMode = inputs.mode === 'room';
  const hasCeiling = inputs.includeCeiling && result.ceilingArea > 0;
  const totalLitres = hasCeiling ? result.totalCombinedPaintRequired : result.finalPaintRequired;
  const recommendedLitres = hasCeiling ? result.totalCombinedRecommendedLitres : result.recommendedLitres;

  const handleCopySummary = () => {
    const summaryText = `ProjectTally — Paint Specification:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- Total Paint Needed: ${totalLitres.toFixed(1)} L
- Recommended Purchase: ${recommendedLitres.toFixed(1)} L (incl. ${inputs.wasteAllowance}% waste allowance)
- Wall Finish / Swatch: ${inputs.wallColorName || 'Standard'} (${inputs.paintCoverage} m²/L spread rate)
- Net Wall Area: ${result.paintableArea.toFixed(2)} m² (${inputs.coats} coats)
${hasCeiling ? `- Ceiling Area: ${result.ceilingArea.toFixed(2)} m² (${inputs.ceilingCoats} coats, ${result.ceilingPaintRequired.toFixed(1)} L required)\n` : ''}${inputs.costPerLitre > 0 ? `- Estimated Material Cost: $${result.estimatedTotalCost.toFixed(2)} (@ $${inputs.costPerLitre}/L)\n` : ''}- Suggested Cans: ${[
      result.canBreakdown.cans10L ? `${result.canBreakdown.cans10L}×10L` : '',
      result.canBreakdown.cans5L ? `${result.canBreakdown.cans5L}×5L` : '',
      result.canBreakdown.cans2_5L ? `${result.canBreakdown.cans2_5L}×2.5L` : '',
      result.canBreakdown.cans1L ? `${result.canBreakdown.cans1L}×1L` : '',
    ].filter(Boolean).join(', ') || 'None'}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by ProjectTally — Measure. Calculate. Build.`;

    navigator.clipboard.writeText(summaryText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div
      id="calculation-certificate"
      className="bg-[#1A1918] text-[#F8F7F4] rounded-xl p-6 lg:p-8 flex flex-col justify-between shadow-lg relative overflow-hidden border border-[#2D2B28] print:border-none print:shadow-none print:bg-white print:text-black"
      aria-live="polite"
      role="region"
      aria-label="Paint calculation results and specifications"
    >
      {/* Subtle architectural grid watermark in corner */}
      <div className="absolute top-0 right-0 w-32 h-32 opacity-5 pointer-events-none technical-grid print:hidden" />

      <div>
        {/* Top Tag & Actions Bar */}
        <div className="flex items-center justify-between pb-4 border-b border-[#33312E] print:border-black/20 mb-6">
          <div className="flex items-center gap-2">
            <span
              className="w-2.5 h-2.5 rounded-full"
              style={{ backgroundColor: inputs.wallColorHex || '#C2410C' }}
            />
            <span className="font-mono text-xs tracking-widest text-[#A8A29E] print:text-black uppercase">
              SPECIFICATION CERTIFICATE
            </span>
          </div>

          <div className="flex items-center gap-2 print:hidden">
            <button
              id="print-specs-btn"
              type="button"
              onClick={handlePrint}
              className="flex items-center gap-1.5 text-xs font-mono text-[#D6D3CD] hover:text-white px-2.5 py-1 rounded bg-[#2D2B28] hover:bg-[#3D3A36] transition-colors cursor-pointer"
              title="Print calculation sheet or save as PDF"
            >
              <Printer className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">PRINT</span>
            </button>

            <button
              id="copy-summary-btn"
              type="button"
              onClick={handleCopySummary}
              className="flex items-center gap-1.5 text-xs font-mono text-[#D6D3CD] hover:text-white px-2.5 py-1 rounded bg-[#2D2B28] hover:bg-[#3D3A36] transition-colors cursor-pointer"
              title="Copy measurement summary to clipboard"
            >
              {copied ? (
                <>
                  <Check className="w-3.5 h-3.5 text-emerald-400" />
                  <span>COPIED</span>
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5" />
                  <span>COPY SPECS</span>
                </>
              )}
            </button>
          </div>
        </div>

        {/* Warning if excessive openings */}
        {result.hasExcessiveOpenings && (
          <div className="mb-6 p-4 bg-amber-950/40 border border-amber-500/40 rounded-lg flex items-start gap-3 text-amber-200 text-xs print:bg-white print:text-red-700 print:border-red-500">
            <AlertTriangle className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
            <div>
              <p className="font-medium">Openings exceed wall area</p>
              <p className="text-amber-300/80 print:text-red-600 mt-1">
                Your doors and windows total {result.excludedArea.toFixed(1)} m², which is larger than the total wall surface of {result.totalWallArea.toFixed(1)} m². Please check your room dimensions.
              </p>
            </div>
          </div>
        )}

        {/* PRIMARY PROMINENT DISPLAY */}
        <div className="space-y-1 mb-7">
          <div className="flex items-center justify-between">
            <span className="font-mono text-xs text-[#A8A29E] print:text-black/60 tracking-widest uppercase">
              {hasCeiling ? 'TOTAL ESTIMATED VOLUME (WALLS + CEILING)' : 'YOU NEED'}
            </span>
            <span className="text-xs font-mono text-[#C2410C] font-semibold">
              {inputs.wallColorName}
            </span>
          </div>
          <div className="flex items-baseline gap-3 flex-wrap">
            <span className="text-5xl sm:text-6xl font-serif font-bold text-white print:text-black tracking-tight">
              {totalLitres.toFixed(1)}
            </span>
            <span className="text-xl sm:text-2xl font-serif font-light text-[#D6D3CD] print:text-black/70">
              LITRES OF PAINT
            </span>
          </div>

          {hasCeiling && (
            <div className="text-xs font-mono text-[#A8A29E] print:text-black/60 pt-1 flex items-center gap-2">
              <span>Walls: {result.finalPaintRequired.toFixed(1)}L</span>
              <span>•</span>
              <span>Ceiling: {result.ceilingPaintRequired.toFixed(1)}L</span>
            </div>
          )}
        </div>

        {/* RECOMMENDED PURCHASE CALLOUT */}
        <div className="bg-[#242220] print:bg-stone-50 border border-[#383531] print:border-stone-200 rounded-lg p-5 mb-7">
          <div className="flex items-center justify-between mb-1">
            <div className="font-mono text-[11px] text-[#C2410C] font-semibold tracking-wider uppercase">
              RECOMMENDED PURCHASE
            </div>
            <div className="text-[11px] font-mono text-[#A8A29E] print:text-black/60">
              Rounded for retail
            </div>
          </div>
          <div className="flex items-baseline gap-2">
            <span className="text-3xl font-serif font-bold text-white print:text-black">
              {recommendedLitres.toFixed(1)}
            </span>
            <span className="text-sm font-sans text-[#D6D3CD] print:text-black/70">
              litres
            </span>
          </div>
          <p className="text-xs text-[#A8A29E] print:text-black/70 mt-1.5 flex items-center gap-1.5">
            <Info className="w-3.5 h-3.5 text-[#C2410C] shrink-0" />
            <span>Including {inputs.wasteAllowance}% waste allowance for cutting-in, roller absorption & spills.</span>
          </p>

          {/* Practical Can Sizing Breakdown */}
          {recommendedLitres > 0 && (
            <div className="mt-4 pt-3 border-t border-[#33312E] print:border-stone-200">
              <div className="text-[11px] font-mono text-[#A8A29E] print:text-black/60 uppercase mb-2 flex items-center gap-1.5">
                <Package className="w-3 h-3 text-[#D6D3CD] print:text-black" />
                <span>Suggested Can Sizing Distribution</span>
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-center">
                {result.canBreakdown.cans10L > 0 && (
                  <div className="bg-[#1A1918] print:bg-stone-100 p-2 rounded border border-[#3D3A36] print:border-stone-300">
                    <div className="text-base font-bold text-white print:text-black">
                      {result.canBreakdown.cans10L}×
                    </div>
                    <div className="text-[10px] font-mono text-[#A8A29E] print:text-black/70">10L Tin</div>
                  </div>
                )}
                {result.canBreakdown.cans5L > 0 && (
                  <div className="bg-[#1A1918] print:bg-stone-100 p-2 rounded border border-[#3D3A36] print:border-stone-300">
                    <div className="text-base font-bold text-white print:text-black">
                      {result.canBreakdown.cans5L}×
                    </div>
                    <div className="text-[10px] font-mono text-[#A8A29E] print:text-black/70">5L Tin</div>
                  </div>
                )}
                {result.canBreakdown.cans2_5L > 0 && (
                  <div className="bg-[#1A1918] print:bg-stone-100 p-2 rounded border border-[#3D3A36] print:border-stone-300">
                    <div className="text-base font-bold text-white print:text-black">
                      {result.canBreakdown.cans2_5L}×
                    </div>
                    <div className="text-[10px] font-mono text-[#A8A29E] print:text-black/70">2.5L Tin</div>
                  </div>
                )}
                {result.canBreakdown.cans1L > 0 && (
                  <div className="bg-[#1A1918] print:bg-stone-100 p-2 rounded border border-[#3D3A36] print:border-stone-300">
                    <div className="text-base font-bold text-white print:text-black">
                      {result.canBreakdown.cans1L}×
                    </div>
                    <div className="text-[10px] font-mono text-[#A8A29E] print:text-black/70">1L Tin</div>
                  </div>
                )}
              </div>
            </div>
          )}
        </div>

        {/* OPTIONAL ESTIMATED COST CALLOUT */}
        {inputs.costPerLitre > 0 && (
          <div className="bg-[#242220] print:bg-stone-50 border border-[#383531] print:border-stone-200 rounded-lg p-4 mb-7 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Coins className="w-4 h-4 text-[#C2410C]" />
              <div>
                <div className="font-mono text-[11px] text-[#A8A29E] print:text-black/60 uppercase">
                  Estimated Paint Cost
                </div>
                <div className="text-xs text-[#D6D3CD] print:text-black/70">
                  Based on ${inputs.costPerLitre.toFixed(2)}/L
                </div>
              </div>
            </div>
            <div className="text-xl font-serif font-bold text-white print:text-black font-mono">
              ${result.estimatedTotalCost.toFixed(2)}
            </div>
          </div>
        )}

        {/* DETAILED MEASUREMENT BREAKDOWN TABLE */}
        <div className="space-y-3">
          <div className="text-xs font-mono text-[#A8A29E] print:text-black/70 uppercase tracking-wider flex items-center justify-between">
            <span>Engineering Breakdown</span>
            <span>Metric Specs</span>
          </div>

          <div className="divide-y divide-[#2B2926] print:divide-stone-200 text-xs font-mono">
            <div className="py-2 flex justify-between items-center text-[#D6D3CD] print:text-black/80">
              <span className="text-[#A8A29E] print:text-black/60">
                {isRoomMode
                  ? `Room Wall Perimeter (${inputs.roomLength}m × ${inputs.roomWidth}m)`
                  : `Gross Wall Span (${inputs.wallCount} walls)`}
              </span>
              <span className="text-white print:text-black font-medium">{result.totalWallArea.toFixed(2)} m²</span>
            </div>

            <div className="py-2 flex justify-between items-center text-[#D6D3CD] print:text-black/80">
              <span className="text-[#A8A29E] print:text-black/60">
                Excluded Openings ({inputs.doorCount} doors, {inputs.windowCount} windows)
              </span>
              <span className="text-[#C2410C]">−{result.excludedArea.toFixed(2)} m²</span>
            </div>

            <div className="py-2 flex justify-between items-center text-[#D6D3CD] print:text-black/80 font-medium bg-[#22201E]/60 print:bg-stone-100 px-2 rounded">
              <span className="text-white print:text-black">Net Paintable Wall Area</span>
              <span className="text-white print:text-black font-bold">{result.paintableArea.toFixed(2)} m²</span>
            </div>

            {hasCeiling && (
              <div className="py-2 flex justify-between items-center text-[#D6D3CD] print:text-black/80">
                <span className="text-[#A8A29E] print:text-black/60">
                  Ceiling Area ({inputs.ceilingCoats} coats)
                </span>
                <span className="text-white print:text-black font-medium">+{result.ceilingArea.toFixed(2)} m²</span>
              </div>
            )}

            <div className="py-2 flex justify-between items-center text-[#D6D3CD] print:text-black/80">
              <span className="text-[#A8A29E] print:text-black/60">Number of Coats</span>
              <span className="text-white print:text-black">{inputs.coats} coats</span>
            </div>

            <div className="py-2 flex justify-between items-center text-[#D6D3CD] print:text-black/80">
              <span className="text-[#A8A29E] print:text-black/60">Paint Spread Rate</span>
              <span className="text-white print:text-black">{inputs.paintCoverage} m²/L</span>
            </div>

            <div className="py-2 flex justify-between items-center text-[#D6D3CD] print:text-black/80">
              <span className="text-[#A8A29E] print:text-black/60">Waste Margin (+{inputs.wasteAllowance}%)</span>
              <span className="text-[#D6D3CD] print:text-black/80">+{result.wastePaintRequired.toFixed(2)} L</span>
            </div>

            <div className="py-2.5 flex justify-between items-center text-sm font-bold text-white print:text-black pt-3 border-t-2 border-[#3D3A36] print:border-stone-400">
              <span>Final Recommended Volume</span>
              <span className="text-[#C2410C] font-mono text-base">{recommendedLitres.toFixed(1)} L</span>
            </div>
          </div>
        </div>
      </div>

      {/* Workshop standard note */}
      <div className="mt-8 pt-4 border-t border-[#2D2B28] print:border-stone-300 text-[11px] text-[#73716B] print:text-black/60 flex items-center justify-between">
        <span>Standard ISO/DIN 13300 Architectural Paint Model</span>
        <span className="font-mono">VERIFIED WORKSHOP MATH</span>
      </div>
    </div>
  );
}

